export const skills = [
  {
    category: "Cloud & Infrastructure",
    items: [
      "AWS",
      "EKS",
      "ECR",
      "EC2",
      "ECS",
      "S3",
      "RDS",
      "Lambda",
      "VPC",
      "IAM",
      "CloudFront",
      "Route 53",
      "ACM",
      "CloudTrail",
      "Linux",
      "Networking",
      "DNS",
      "Load balancing",
    ],
  },
  {
    category: "Kubernetes & Platform",
    items: [
      "Kubernetes",
      "EKS",
      "Helm",
      "ArgoCD",
      "FluxCD",
      "GitOps",
      "AWS Load Balancer Controller",
      "Gateway API",
      "ExternalDNS",
      "cert-manager",
      "Karpenter",
      "KEDA",
      "Kyverno",
      "Velero",
      "Vault",
    ],
  },
  {
    category: "Infrastructure as Code & Delivery",
    items: [
      "Terraform",
      "CloudFormation",
      "GitHub Actions",
      "GitLab CI/CD",
      "OIDC federation",
      "Infrastructure automation",
    ],
  },
  {
    category: "Observability",
    items: [
      "Prometheus",
      "Grafana",
      "Alertmanager",
      "OpenTelemetry",
      "Elasticsearch/Kibana",
      "EFK",
      "CloudWatch",
      "PagerDuty",
    ],
  },
  {
    category: "Security & Access",
    items: [
      "IAM",
      "IRSA",
      "Kubernetes RBAC",
      "Zero Trust",
      "Secrets management",
      "AWS Secrets Manager",
    ],
  },
  {
    category: "AI-Assisted Engineering",
    items: [
      "Claude Code",
      "CLAUDE.md",
      "Custom skills",
      "MCP integrations",
      "AWS Bedrock",
      "Context engineering",
      "AI-assisted code review",
    ],
  },
  {
    category: "Programming",
    items: ["Python", "Bash", "SQL"],
  },
];
